# Server
server:
  port: 8000
  tomcat:
    uri-encoding: UTF-8

spring:

# Datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.117.155:3306/gulimall_ums?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: KAG1823
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 10
      min-idle: 5
      time-between-connect-error-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000
      validation-query: SELECT 1 FROM DUAL

# Nacos
  application:
    name: gulimall-member
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.117.155:8848

# MybatisPlus
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: top.parak.gulimall.member.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      id-type: auto

