# Server
server:
  port: 10000
  tomcat:
    uri-encoding: UTF-8

spring:

# Nacos
  application:
    name: gulimall-product
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.117.155:8848

  # Json
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# Datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.117.155:3306/gulimall_pms?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: KAG1823
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 10
      min-idle: 5
      time-between-connect-error-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000
      validation-query: SELECT 1 FROM DUAL

# Redis
  redis:
    host: 192.168.117.155
    port: 6379
    database: 0
    password: KAG1823

# Cache
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      # 是否使用前缀
      use-key-prefix: true
      # 优先使用指定的前缀，没有指定则使用逻辑分区作为前缀
      # key-prefix: CACHE_
      # 缓存空值，防止缓存穿透
      cache-null-values: true

  # Thymeleaf
  thymeleaf:
    encoding: UTF-8
    enabled: true
    cache: false

# MybatisPlus
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: top.parak.gulimall.product.entity
  configuration:
    map-underscore-to-camel-case: true
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false

# Log
logging:
  level:
    top.parak.gulimall.product.dao: info
