# Server
server:
  port: 25000
  tomcat:
    uri-encoding: UTF-8

# Spring
spring:

# MVC
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

# Alibaba
  application:
    name: gulimall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.117.155:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8333
        port: 8719

  # RabbitMQ
  rabbitmq:
    host: 192.168.117.155
    port: 5672
    username: parak
    password: KAG1823
    virtual-host: /gulimall
    publisher-confirm-type: correlated
    template:
      mandatory: true
    listener:
      direct:
        acknowledge-mode: manual

# Redis
  redis:
    host: 192.168.117.155
    port: 6379
    database: 0
    password: KAG1823

# Session
  session:
    store-type: redis
    redis:
      namespace: gulimall:session
    timeout: 6000

# Thymeleaf
  thymeleaf:
    encoding: UTF-8
    enabled: true
    cache: false

# MybatisPlus
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: top.parak.gulimall.order.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      id-type: auto

# Custom
gulimall:

# Thread
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

# RabbitMQ
  rabbitmq:
    seckill:
      exchange: order-event-exchange
      routing-key: order.seckill.order

# AliPay
  alipay:
    app-id: 2021000119601155
    notify-url: http://jbaksd.natappfree.cc/payed/notify
    return-url: http://member.gulimall.com/memberOrder.html
    sign-type: RSA2
    charset: utf-8
    timeout: 15m

# Actuator
#management:
#  endpoints:
#    web:
#      exposure:
#        exclude: *
