server:
  port: 30000

spring:

# Application
  application:
    name: gulimall-third-party

# Nacos
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.117.155:8848

# OSS
    alicloud:
      access-key: LTAI5tNX5UroFeTYGf9GjtGD
      secret-key: rj3UWP6LiKkIUreE3hN1Q1VH5ebPkk
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: khighness-gulimall
